### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by mlabate** [redwoodjs/learn.redwoodjs.com#102]
Hello,
@clairefro I wish to contribute to translate Redwood tutorials to Italian.
Is it possible?

**Comment by clairefro** [comment]
Hi! Thanks for volunteering :) I have added Italian to our Crowdin repo

https://crowdin.com/project/learn-redwoodjs

Are you a native or near native Italian speaker? If so, go ahead and request access to the above repo and I'll help you get started

**Comment by clairefro** [comment]
Here are the links to the translation guide to get started 
https://github.com/redwoodjs/learn.redwoodjs.com/blob/main/README_TRANSLATION_GUIDE.md

I will approve your request to enter the Crowdin repo if you visit the link in previous comment.

Feel free to reach out in [discord](https://discord.gg/jjSYEQd) translation channels if you have any questions about translation

**Comment by mlabate** [comment]
Hello Claire,
yes I'm a native Italian speaker.
I've just sent my request to join Crowdin repo. :smile: 
Thank you

**Comment by clairefro** [comment]
You're in! Welcome :)
