### ISSUE TITLE
Native Italian Translator

### ISSUE THREAD

**Issue by derkanadier** [redwoodjs/learn.redwoodjs.com#138]
Hello @clairefro,

I am fluent in Italian (native), English and French.

I would like to contribute to the translation of the _RedwoodJS_ documentation (English --> Italian).

It would be my pleasure to participate in the growth of this community.

**Comment by clairefro** [comment]
Hi @derkanadier ! We'd love your help. Check out our [translation guide](https://github.com/redwoodjs/learn.redwoodjs.com/blob/main/README_TRANSLATION_GUIDE.md), then head over to [Crowdin](https://crowdin.com/project/learn-redwoodjs) to request translator access in the respective languages.
