### ISSUE TITLE
Update Tutorial 2 for new scenario `data` attribute

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/learn.redwoodjs.com#148]
## Wait For Merge!

Needs https://github.com/redwoodjs/redwood/pull/3261 to be released before merging this!

@callingmedic911 did you want to update these as well?

**Comment by callingmedic911** [comment]
Oops! Missed this repo. I'll get it done by tomorrow. Does that work @cannikin?

**Comment by cannikin** [comment]
No rush! We'll be releasing this with 0.37.0 so we've got a week or so. :)
