### ISSUE TITLE
Add Plausible Analytics 

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/learn.redwoodjs.com#151]
@clairefro We want to add a really simple analytics package to the site, but I can't figure out where to put this `<script>` tag. 😕 This is much easier in CameronJS. 😉

```html
<script defer data-domain="learn.redwoodjs.com" src="https://plausible.io/js/plausible.js"></script>
```

**Comment by clairefro** [comment]
Luckily it's as easy as adding a line to the config!
https://plausible.io/docs/docusaurus-integration

same with cameronjs? :)

**Comment by clairefro** [comment]
(I'd make the PR for you, but maybe it's best someone with the analytics account can do a couple test clicks around the GitHub preview deploy and see if hits are recorded?

**Comment by cannikin** [comment]
> same with cameronjs? :)

You just paste the actual HTML the way Dog intended!!!!!!!!!!!!!!!!!!!!!  😭

**Comment by cannikin** [comment]
Thanks, BTW! I'll just push it live, the start showing data REAL quick and it's hard to mess up.

**Comment by cannikin** [comment]
Hmm, just realized this probably won't work since Docusaurus doesn't make AN ACTUAL WEBSITEEEEEEEE  React ain't gonna count anything but the first page request. Grrrr

**Comment by cannikin** [comment]
Cancel that, they thought of everything!

If you want access to the Plausible dashboard @clairefro gimmie your email and I'll invite you!
