### ISSUE TITLE
Redwood file structure not up to date 

### ISSUE THREAD

**Issue by khabubuphathu** [redwoodjs/learn.redwoodjs.com#177]
In the tutorial for Learn RedwoodJS, the file structure is not up to date with v0.41.0. I noticed the following issues:

1. Instead of two top level directories which are `api` and `web`, we now have three `api`,`web` and `scripts` which contains the seed script which is no longer in `api/db` directory.
2. The tutorial mentions that the `api/src/lib` contains only one file but it now contains three files which are `auth.js`, `db.js` and `logger.js`.

Looks like a quick win, I don't mind contributing.

**Comment by Tobbe** [comment]
We love contributions 😃

If you make a PR and tag me I can have a look

**Comment by khabubuphathu** [comment]
#173 Covers the changes I mentioned above, So I think this issue can be closed? Thanks for point out a pr to bring the tutorial  in line with v1 exists

**Comment by clairefro** [comment]
Thanks for looking into this, @khabubuphathu! Closing as issue being addressed
