### ISSUE TITLE
An Issue I spotted regarding Cells tutorial

### ISSUE THREAD

**Issue by berkerdemirer** [redwoodjs/learn.redwoodjs.com#183]
Hello,

It could be that I made a mistake but I just wanted to point it out anyway. While following the tutorial I encountered an issue with the Cell that I created for blog posts. Although I changed the query type to `posts` as suggested in the tutorial and as it is like that in the GraphQL schema, I am still getting an error like `Cannot query field "posts" on type "Query".GraphQL: Validation` and returned result is empty.

This is the type I have in posts.sdl.js
` type Query {
    posts: [Post!]! @requireAuth
    post(id: Int!): Post @requireAuth
  }`

and query in the cell

` query BlogPostsQuery {
    posts {
      id
    }
  }
`

https://learn.redwoodjs.com/docs/tutorial/cells

Edit: I realised that this issue persist in all the graphql related files

**Comment by clairefro** [comment]
@cannikin have you run into this issue before?

**Comment by cannikin** [comment]
Hmm I have not. Are those code samples you pasted what’s actually in your code? Are there no newlines in those queries? I think they’re required inside to delineate certain parts. 

If there ARE newlines, maybe try restarting the dev server @berkerdemirer?

**Comment by cannikin** [comment]
Hey any @berkerdemirer were you able to get this working? No pressure, but I'm just going through and cleaning up issues and would like to close this if it's resolved. :)

**Comment by standup75** [comment]
I just ran into the same issue, I think VS Code has some issues updating types dynamically, restarting VS Code made that error disappear

**Comment by cloudify** [comment]
I just encountered this same issue, restarting vscode fixed it as well.
