### ISSUE TITLE
Tutorial1: Second Page code snippet doesn't reflect code generated.

### ISSUE THREAD

**Issue by jacebenson** [redwoodjs/learn.redwoodjs.com#208]
I ran through part 1 of the tutorial today to test this for the team (yay).

I found a number of things I wanted to verify or fix.

On https://learn.redwoodjs.com/docs/tutorial/a-second-page-and-a-link the code snippet for `// web/src/pages/HomePage/HomePage.js`.

It has two sections highlighted that don't make sense, but also the code is different.

Should this be highlighting `<nav>...</nav>` and not highlighting the import (as it is there by default now)?

**Comment by jtoar** [comment]
Thanks! I saw this as well and have a PR up for it. Fix is in the works!

**Comment by jacebenson** [comment]
Great!  Thanks @jtoar
