### ISSUE TITLE
Tutorial 1: Cells - Code doesn't match generated code, and highlight seems off.

### ISSUE THREAD

**Issue by jacebenson** [redwoodjs/learn.redwoodjs.com#209]
Page: https://learn.redwoodjs.com/docs/tutorial/cells

> maybe we should update the /cells tutorial to match the ./web/src/components/Post/PostsCell file instead of the differnt code on the tutorial. 

> higlighting odd lines in the rename articles query code snippet, we should be highlighing export const Success = ({posts}) and not `)`, same with `return (`

> Really just looking at all the code highlights, they should prbably all be looked at.

**Comment by jtoar** [comment]
Thanks! I've included this fix in https://github.com/redwoodjs/redwood/pull/4781.

**Comment by jacebenson** [comment]
Thanks!
