### ISSUE TITLE
Tutorial 1: Routing Params code highlight incorrect

### ISSUE THREAD

**Issue by jacebenson** [redwoodjs/learn.redwoodjs.com#210]
on [/routing-params,](https://learn.redwoodjs.com/docs/tutorial/routing-params) the higlighted code for adding `<Route ... /article/{id}` is wrong

![image](https://user-images.githubusercontent.com/638764/158041473-6bbd94fc-755f-4e63-9f08-f572cb6bc138.png)

**Comment by jtoar** [comment]
Thanks! I've fixed that in main.

**Comment by jacebenson** [comment]
Thansk!
