### ISSUE TITLE
Tutorial 1: Authentication - highlight model to add "User"

### ISSUE THREAD

**Issue by jacebenson** [redwoodjs/learn.redwoodjs.com#211]
on [/authentication](https://learn.redwoodjs.com/docs/tutorial/authentication), maybe highlight the user model to add on schema.primsa

![image](https://user-images.githubusercontent.com/638764/158041560-7e9f9dda-ad52-486f-9e00-aef20b3dde33.png)

**Comment by jacebenson** [comment]
I can't seem to do a clean update the js should be ````javascript {28,36} above the schema.prisma file block

**Comment by jtoar** [comment]
Good call! I've included this in https://github.com/redwoodjs/redwood/pull/4781.

**Comment by jacebenson** [comment]
Thanks!
