### ISSUE TITLE
Tutorial 2: our-first-test within is not defined

### ISSUE THREAD

**Issue by snettah** [redwoodjs/learn.redwoodjs.com#219]
Hello,

in this section of the tutorial we use `within` in the ArticlesCell.test.js but I have an error with this.

node: v16.8.0
yarn: v1.22.11
macos
based on sample repo.

```
    ReferenceError: within is not defined

      29 |       const truncatedBody = article.body.substring(0, 10)
      30 |       const matchedBody = screen.getByText(truncatedBody, { exact: false })
    > 31 |       const ellipsis = within(matchedBody).getByText('...', { exact: false })
```

**Comment by snettah** [comment]
[PR](https://github.com/redwoodjs/learn.redwoodjs.com/pull/220)

**Comment by snettah** [comment]
https://github.com/redwoodjs/learn.redwoodjs.com/pull/221

**Comment by jtoar** [comment]
Closed by https://github.com/redwoodjs/learn.redwoodjs.com/pull/221.
