### ISSUE TITLE
Dark mode makes it difficult to read highlighted words

### ISSUE THREAD

**Issue by Thieffen** [redwoodjs/learn.redwoodjs.com#24]
At least this is the case on my screen...
Anybody with a well calibrated screen (Apple devices?) to confirm ?

![image](https://user-images.githubusercontent.com/847877/104239745-4b7a5e80-545b-11eb-88c6-8c4152fa3a96.png)

**Comment by cannikin** [comment]
Can confirm! Lemmie see if I can invent some CSS here...

**Comment by Thieffen** [comment]
Thanks!
