### ISSUE TITLE
Change footer colors to be more accessible

### ISSUE THREAD

**Issue by clairefro** [redwoodjs/learn.redwoodjs.com#31]
Our page has lovely theming now thanks to Rob but I noticed our footer is somewhat hard to read in light mode. 

There is not enough contrast between the dark gray bg and dark red text. 

The dark red text is similarly hard to read on dark red bg in dark mode

Light mode
![image](https://user-images.githubusercontent.com/9841162/105443507-bb89a100-5c20-11eb-86fb-c704b032c6ca.png)

Dark mode
![image](https://user-images.githubusercontent.com/9841162/105443534-c9d7bd00-5c20-11eb-9088-42e10b81d116.png)

**Comment by ShrillShrestha** [comment]
Can you guide me to the file that needs changing to achieve the solution? I am trying to learn open-source, so, please forgive my novice question.

**Comment by clairefro** [comment]
Hi @ShrillShrestha ! Thanks for reaching out 

I am putting this issue on hold temporarily as it appears some bug is making `master` branch appear different in production vs. development. 

But to answer your question, this is a style issue so as a hint you would be looking for a `.css` file ;). You would be able to find which css selectors to target by using your browser inspector tool and clicking around the footer

**Comment by rijusougata13** [comment]
is it still a issue or the issue solved? if the issue still exist assign me

**Comment by clairefro** [comment]
Resolved by #37
