### ISSUE TITLE
Our first tiny UI translation! The footer 

### ISSUE THREAD

**Issue by clairefro** [redwoodjs/learn.redwoodjs.com#32]
There are two types of content we must translate: markdown docs and UI strings.

We've already gotten started with markdown translation flow, but haven't tried any UI strings yet (= strings NOT in markdown, like in navbar, sidebar, footer, etc)

There is a how-to in the [unreleased i18n docs](https://deploy-preview-4014--docusaurus-2.netlify.app/classic/docs/next/i18n/introduction/#translation-files). See section "JSON files" and the file tree diagram beneath.

As a first baby step for understanding UI string translation in Docusaurus 2, we can **translate the footer into French**. 

Docs -> Docs
Community -> Communauté
More -> Plus
Built with Docusaurus -> Construit avec Docusaurus

_*I do not speak French - if you have a better translation please feel free to use! The purpose of this exercise is to understand UI string translation structure_

![image](https://user-images.githubusercontent.com/9841162/105444580-f391e380-5c22-11eb-9175-16cbc83ac4e6.png)

**Comment by ShrillShrestha** [comment]
Hi, I am a beginner and I would like to contribute to this issue. Can you guide me solve this? Right now, I am looking over the [unreleased i18n docs](https://deploy-preview-4014--docusaurus-2.netlify.app/classic/docs/next/i18n/introduction/#translation-files).

**Comment by clairefro** [comment]
Thanks for stepping up! Feel free to ask questions once you've had a look at the docs

**Comment by ShrillShrestha** [comment]
@clairefro thanks for the reply. I couldn't reply early because it's just morning here. I will start working on it now.

**Comment by ShrillShrestha** [comment]
@clairefro, can you review my PR and give me some feedback if I need to change anything?

**Comment by clairefro** [comment]
Resolved by #36
