### ISSUE TITLE
a11y: low contrast for `span.token.comment` in code blocks

### ISSUE THREAD

**Issue by M0nica** [redwoodjs/learn.redwoodjs.com#38]
I noticed on the site that the contrast value for `span.token.comment` is currently too low (in both light and dark mode) to be accessible as it is 1.64. Generally the minimum contrast level to be accessible is 4.5:1 for AA or 3:1 for large text. 

I was able to encounter this issue by going to https://learn-redwood.netlify.app/docs/tutorial/cells and viewing the code example that contains `// web/src/components/BlogPostsCell/BlogPostsCell.js` at the top (screenshot below)

![Screen Shot 2021-01-22 at 1 55 57 PM](https://user-images.githubusercontent.com/6998954/105533056-a9a80c80-5cb9-11eb-8130-47b99a1eb985.png)

visually the contrast looked too low for me, I used the Google Developer Tools to confirm the contrast level. 

![Screen Shot 2021-01-22 at 1 55 48 PM](https://user-images.githubusercontent.com/6998954/105533058-a9a80c80-5cb9-11eb-80cd-1efecf8ae234.png)

I am available to work on resolving this issue.

**Comment by cannikin** [comment]
I had some additional code block changes (including a darker background) but those styles aren't showing in certain environments! So strange, but I can't comprehend all the combined processes that are in place to make CSS in the modern JS world. :(

I'll see what I can do!

**Comment by clairefro** [comment]
^ I fixed the bug that was causing dev/prod style differences 

However, it looks like we could still improve contrast of comments in code blocks 

![image](https://user-images.githubusercontent.com/9841162/105644671-9af15f00-5e4b-11eb-9957-28711a7cf0e3.png)

**Comment by M0nica** [comment]
@clairefro Great, I am glad the styling issue between dev and staging is sorted out now. I just opened a PR (https://github.com/redwoodjs/learn.redwoodjs.com/pull/42) to improve the contrast of comments in code blocks.

**Comment by clairefro** [comment]
Resolved by #42
