### ISSUE TITLE
a11y: low contrast for some text in nav and footer

### ISSUE THREAD

**Issue by M0nica** [redwoodjs/learn.redwoodjs.com#39]
Similar to https://github.com/redwoodjs/learn.redwoodjs.com/issues/38 I noticed on the site that the contrast value for certain text in the footer and navigation is currently too low to be accessible. Generally the minimum contrast level to be accessible is 4.5:1 for AA or 3:1 for large text.

Screenshots below:

![Screen Shot 2021-01-22 at 2 05 10 PM](https://user-images.githubusercontent.com/6998954/105534160-140d7c80-5cbb-11eb-96fd-a6876a3fa003.png)
![Screen Shot 2021-01-22 at 2 04 57 PM](https://user-images.githubusercontent.com/6998954/105534163-14a61300-5cbb-11eb-8cd9-c77fc412c1c3.png)
![Screen Shot 2021-01-22 at 2 04 18 PM](https://user-images.githubusercontent.com/6998954/105534166-14a61300-5cbb-11eb-9ff4-de6f878212d2.png)
![Screen Shot 2021-01-22 at 2 04 10 PM](https://user-images.githubusercontent.com/6998954/105534167-153ea980-5cbb-11eb-9000-d7284c617219.png)

I am happy to work on updating the colors in the footer and navigation to be more accessible but am not sure in terms of branding what colors would be appropriate.

**Comment by M0nica** [comment]
@cannikin it would be helpful to get your input on making the color schemes more accessible as my understanding is you worked on the initial color schemes.

**Comment by cannikin** [comment]
Yep I'll take a look at these, thanks for pointing them out!

**Comment by cannikin** [comment]
Addressing this in #45
