### ISSUE TITLE
Rename master -> main

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/learn.redwoodjs.com#46]
This should be a pretty simple change on GitHub's end, and then just need to let Netlify know to build a different default branch.

**Comment by cannikin** [comment]
I can take this one @clairefro unless you want to experience more devops fun!

**Comment by clairefro** [comment]
i do love me some devops :) Do you mind if i take this one on? I'd like to sync Crowdin's config at the same time

**Comment by cannikin** [comment]
Please do! I'm a whole-hearted believer in the programmer's maxim that "laziness is a virtue" so letting someone else do the work is the laziest and, therefore, most virtuous course of action. :)

**Comment by clairefro** [comment]
`master` is now `main` 

For those needing to update their local :

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```
