### ISSUE TITLE
Tutorial page -> [Edit this page link]

### ISSUE THREAD

**Issue by TawfikYasser** [redwoodjs/learn.redwoodjs.com#47]
Hi

I think the `Edit this page` link doesn’t work in the Tutorial page -> [Welcome to Redwood ](https://learn-redwood.netlify.app/docs/tutorial/welcome-to-redwood)

And I think also all `Edit this page` link in all the tutorial doesn’t work. 👇

![Img-1](https://user-images.githubusercontent.com/54971231/106634543-8b2ef480-6588-11eb-96f6-0ba0ab110dce.png)

When clicking on it, It displays `Not found` 👇

![Img-2](https://user-images.githubusercontent.com/54971231/106634734-bb769300-6588-11eb-89c7-3e18a1adc34e.png)

I think this because the link provided in `href` as follows : <a href="https://github.com/redwoodjs/learn.redwoodjs.com/docs/tutorial/welcome-to-redwood.md">Edit this page</a> and this doesn’t work.

It doesn’t go to this page : [welcome-to-redwood.md](https://github.com/redwoodjs/learn.redwoodjs.com/blob/master/docs/tutorial/welcome-to-redwood.md) 👇

![Img-3](https://user-images.githubusercontent.com/54971231/106635586-b534e680-6589-11eb-8519-306cb022e8b2.png)

> If I’m true, <strong>I will be very lucky</strong> to fix this `bug`, And I will ask for a question
> *And If I’m wrong, Sorry and I will be careful again.*

Thanks

**Comment by thedavidprice** [comment]
Looping in @clairefro 

@TawfikYasser recently worked with me to update Redwood Docs -- a first contribution to Redwood repos! Could you take a look here and confirm 1) the redirect is not using the correct domain and 2) what the redirect needs to do (regardless of domain)? This might be sorted once deployed and/or might be a bug with Docusaurus v2. If it's something we can fix on our end, Claire, please do provide @TawfikYasser with some initial direction.

Thanks everyone!

**Comment by TawfikYasser** [comment]
Thanks @thedavidprice , I will do my best
I am waiting for @clairefro :)

**Comment by clairefro** [comment]
Hi @TawfikYasser ! This is indeed a bug. 

It appears that this is set in the `docusaurus.config` file under `presets > docs > editUrl`

Looks like it may need to be changed from 
`https://github.com/redwoodjs/learn.redwoodjs.com/`
to
`https://github.com/redwoodjs/learn.redwoodjs.com/blob/main/`

I'm not sure how to ensure people do not commit directly to `main` when they make edits. Hopefully the branch protection (no merge without review) will take care of this?...

**Comment by TawfikYasser** [comment]
I’m really sorry @clairefro for that.

**Comment by TawfikYasser** [comment]
I will work on a separate branch next time, I promise you. Sorry

**Comment by TawfikYasser** [comment]
Please explain to me how to fix the issue, Because I don’t understand what you said :

> It appears that this is set in the docusaurus.config file under presets > docs > editUrl
Looks like it may need to be changed from
https://github.com/redwoodjs/learn.redwoodjs.com/
to
https://github.com/redwoodjs/learn.redwoodjs.com/blob/main/

**Comment by TawfikYasser** [comment]
@clairefro Do you mean this [line](https://github.com/redwoodjs/learn.redwoodjs.com/blob/main/docusaurus.config.js#L114) ?

**Comment by clairefro** [comment]
> @clairefro Do you mean this [line](https://github.com/redwoodjs/learn.redwoodjs.com/blob/main/docusaurus.config.js#L114) ?

Exactly! That base url should change to one that actually works on Github.
It seems that adding `/blob/main/` might work -could you try that out?

> I’m really sorry @clairefro for that.
I'm not sure what you're apologizing for! No worries, and thank you for taking this on! :)

**Comment by TawfikYasser** [comment]
Okay @clairefro 
I am apologizing about working in the main branch -> If you talking about me 😅
I will try to edit the link now
Thanks and sorry for any misunderstandings

**Comment by TawfikYasser** [comment]
PR opened #50 @clairefro

**Comment by clairefro** [comment]
Resolved by #50 

Thank you!

**Comment by TawfikYasser** [comment]
Great chance for me :)
