### ISSUE TITLE
Fix: authentication link

### ISSUE THREAD

**Issue by TawfikYasser** [redwoodjs/learn.redwoodjs.com#52]
Hi

I think authentication link in the following path `/docs/tutorial/administration.md` [future step](https://github.com/redwoodjs/learn.redwoodjs.com/blob/main/docs/tutorial/authentication) needs to be updated to [this](https://github.com/redwoodjs/learn.redwoodjs.com/blob/main/docs/tutorial/authentication.md)

---

Because it open a `404` page: 👇

![i1](https://user-images.githubusercontent.com/54971231/107175757-51218080-69d6-11eb-998c-1a5f703b3b1f.png)
![i2](https://user-images.githubusercontent.com/54971231/107175762-54b50780-69d6-11eb-9cce-e9bf6da3b8e3.png)

---

Thanks

**Comment by clairefro** [comment]
Hi @TawfikYasser !

The link works in the website where the content is intended to be viewed. It is a relative link without the extension, which is why it's not working in Github.

You can test it out here:
https://learn-redwood.netlify.app/docs/tutorial/administration

**Comment by clairefro** [comment]
Oops, I am reopening this as it does appear to be broken when I opened it in a new tab.

**Comment by TawfikYasser** [comment]
Okay @clairefro

**Comment by clairefro** [comment]
Resolved by #55 - this link no longer appears in the text
