### ISSUE TITLE
Tutorial updates for 0.25

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/learn.redwoodjs.com#53]
@clairefro wanna run that pinecone against the tutorial again?? Just pushed a bunch of changes for the 0.25 release which has a bunch of new prisma commands. It also rearranges the last two steps: Authentication comes before Deployment now. 😬 Is that going to cause problems?

**Comment by clairefro** [comment]
yessir, will do! 

> It also rearranges the last two steps: Authentication comes before Deployment now. grimacing Is that going to cause problems?

No problem at all, will just switch up the order in docusaurus sidebar

**Comment by clairefro** [comment]
Resolved by #55
