### ISSUE TITLE
Algolia search not returning results when switching to French

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/learn.redwoodjs.com#59]
Creating this issue to track our progress around this!

### Current Behavior

When in the English locale all results are English pages. When in the French locale, *nothing* is returned, for english or french words.

### Algolia Config

I don't remember if I asked them to crawl all of `learn-redwood.netlify.app` or just `learn-redwood.netlify.app/en/docs`? In the dashboard that Algolia provides it doesn't let me see what the config currently is.

### Docusaurus Config

It sounds like the Docusaurus peeps think that re-configuring the sitemap should have fixed everything automatically? When I look at the sitemap I see all links like https://learn-redwood.netlify.app/docs/tutorial/cells which don't specify any locale, and going there directly returns the English version of that page, but doesn't redirect to have the `/en` in the path. Maybe we need to directly include links to the French pages in the sitemap? Or does Docusaurus do some magic behind the scenes to tell Algolia about translated equivalent pages?

**Comment by clairefro** [comment]
I checked Sebastien's PR #48 and confirmed that the locale sitemaps are actually located at a different URL!

EN: https://learn-redwood.netlify.app/sitemap.xml
FR: https://learn-redwood.netlify.app/fr/sitemap.xml

^ maybe we need to add the `/fr/` one to algolia so the crawlers know to look for it?

**Comment by cannikin** [comment]
Ahhhhh interesting! So when I requested them to crawl the site I’m pretty sure I gave them just the homepage. I’m not sure how to give them additional URLs (or link them to another sitemap). Lemmie contact support and see if they’ll give me more info.

**Comment by clairefro** [comment]
Thanks Rob!

**Comment by cannikin** [comment]
Support ticket submitted!

However, I'm not clear on how/if the site will only returns results for the locale you're currently viewing, and not just all results across all pages. I'm sure Algolia has some way to facet results by only one thing, like locale, but from my experience that's a lot of manual setup and defining fields so you can only return some records and not others. Maybe Docusaurus 2.0 has all of that figured out and automatically passes the correct options through the search UI that they include? I'm dubious!

Although they do support *versioned* docs and only searching one version or another, right?

**Comment by clairefro** [comment]
I share your curiosity!

"Let's see what happens"

**Comment by clairefro** [comment]
you did some magic!
![image](https://user-images.githubusercontent.com/9841162/109515043-806a6100-7a5b-11eb-8cb3-8825497a8dd7.png)

**Comment by cannikin** [comment]
Awesome! I haven't heard back from my support ticket yet, but I'll take all the credit!

**Comment by cannikin** [comment]
They did end up responding!

> Hi there,
>
> thanks for reaching out!
>
> I've updated your config to add the /fr/ endpoint, > you'll now be able to use the facetFilters language:en or language:fr in your searchParameters!
>
> Hope this answers your question,
> Have a nice day!
