### ISSUE TITLE
Remove Docusaurus example documents, make Tutorial the default section 

### ISSUE THREAD

**Issue by clairefro** [redwoodjs/learn.redwoodjs.com#6]
1. Remove the sections **"Docusaurus"** and **"Features"** that came with Docusaurus by default. 
- Remove from sidebar (`sidebar.js`)
- Remove the docs (all .md files in `docs` outside the `tutorial` dir)
- Remove "Style guide" and "Second Doc" links from footer (replace with tutorial?)
2. Make **"Tutorial"** the default section that is open when you visit `learn.redwood.com/docs`.

This may be trickier than it seems.

![image](https://user-images.githubusercontent.com/9841162/103728697-97c52a80-4f93-11eb-8a6d-cb5acaaaf06a.png)

**Comment by cannikin** [comment]
Is there a way to keep whatever the equivalent of the homepage is (a route?) do a redirect to `/docs/tutorial/welcome-to-redwood`? That way the nav just keeps doing whatever it would normally do.

**Comment by clairefro** [comment]
> Is there a way to keep whatever the equivalent of the homepage is (a route?) do a redirect to `/docs/tutorial/welcome-to-redwood`? 

That would work. It would also be nice to have the tutorial automatically open when navigating to `../docs` directly from outside 

See what's happening here:
https://learn-redwood.netlify.app/docs/

**Comment by cannikin** [comment]
I guess there's the homepage and then everything else starts under /docs? Hmmmmmmmmm You'd think they'd have some way to specify a different starting page rather than forcing you to go to a /docs index page...

**Comment by clairefro** [comment]
There is nothing stopping us from redirecting `/docs` -> `/docs/tutorial/welcome-to-redwood`

It's like redirect leap-frog for those hitting the homepage :)

**Comment by mbush92** [comment]
I think I have this working, I have the website redirecting to the `Welcome to Redwood` tutorial whether it is accessed at the root URL, the Docs link in the nav bar or from Tutorials in the footer.  I have also removed the default docs and removed the two sections from the side bar.  

There is definitely some weird behavior with the side bar, spent quite a while on the sidebar documentation page as well trying to understand how to make it work.  SInce we have an empty `docs` folder we basically have to redirect to the actual document we want to start with.  I tried just redirecting to `/docs/tutorial/` but that did not work and you would also not get the sidebar.

**Comment by clairefro** [comment]
Resolved by #13

**Comment by clairefro** [comment]
> I think I have this working, I have the website redirecting to the `Welcome to Redwood` tutorial whether it is accessed at the root URL, the Docs link in the nav bar or from Tutorials in the footer. I have also removed the default docs and removed the two sections from the side bar.
> 
> There is definitely some weird behavior with the side bar, spent quite a while on the sidebar documentation page as well trying to understand how to make it work. SInce we have an empty `docs` folder we basically have to redirect to the actual document we want to start with. I tried just redirecting to `/docs/tutorial/` but that did not work and you would also not get the sidebar.

Thank you for figuring this out - I was stumped on it for a while! 

I just found a solution for the redirects from `/docs` and `/docs/tutorial` and will open another PR
