### ISSUE TITLE
Typo in the BlogPostCell.js Success section code (Tutorial I)

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/learn.redwoodjs.com#73]
I do not have a Mac computer, so I can only create this issue (instead of a PR)

![image](https://user-images.githubusercontent.com/2712405/111013663-427c0f80-836e-11eb-81d1-fa7733b8077f.png)

and then the same problem below

![image](https://user-images.githubusercontent.com/2712405/111014156-6e989000-8370-11eb-96f4-13d19d8fdff6.png)

**Comment by adriatic** [comment]
I am taking your response as "I will take care of this on a new location)

**Comment by clairefro** [comment]
Hi @adriatic - all the issues from /com repo related to the tutorial were moved to the learn repo 

It is difficult to discern the context of the issue above - can you please make a pull request in the document you wish to suggest changes too with an explanation?

**Comment by adriatic** [comment]
Hi @clairefro 
This typo is fixed and published (see Rob's statement (cannikin transferred this issue from redwoodjs/redwoodjs.com 9 days ago).  I will close this issue now
