### ISSUE TITLE
Finish porting French translations to Crowdin

### ISSUE THREAD

**Issue by clairefro** [redwoodjs/learn.redwoodjs.com#8]
@Thieffen translated the tutorial into French over [here](https://github.com/Thieffen/fr.redwoodjs.com) 

I started moving these translations into our localization management system Crowdin. 
https://github.com/redwoodjs/learn.redwoodjs.com/tree/master/to-upload

This is blocked until I confirm with Thieffen whether he wants to do this himself so he can get credit for his translations in the repo.

**Comment by Thieffen** [comment]
Ciao @clairefro! 
Don't worry you can unblock and proceed with Crowdin.
It's perfectly fine if I do not get any credit for the translation.
I'm quite busy in these days, but I'll try to contribute.

PS: Happy new year ;)

**Comment by clairefro** [comment]
Yo @Thieffen  :) 

I ported your translations to Crowdin.
https://crowdin.com/project/learn-redwoodjs/fr#

A couple are showing as 'incomplete', but it might be a bug in the upload system.

If you have a moment could you take a look at the < 100% ones and tell me if you see a pattern?
- is it from source doc change?
- is it a bug from Crowdin?

(Untranslated content has a light yellow highlight behind text)
![image](https://user-images.githubusercontent.com/9841162/104149093-cecb7f80-5389-11eb-814b-119111f1c6c1.png)

**Comment by clairefro** [comment]
P.S. your hard work is starting to show up on the prototype site for the translations at 100% above!
https://learn-redwood.netlify.app/fr/

**Comment by Thieffen** [comment]
Hello @clairefro !

I went to Crowdin and started to add some more translation.
It looks like a very nice tool, pretty intuitive.
I will try to complete and reach 100% by the end of the week.

Ciao ;)

**Comment by Thieffen** [comment]
Done.

![image](https://user-images.githubusercontent.com/847877/104446409-b2eaf800-559a-11eb-8676-a0cda6981517.png)

**Comment by clairefro** [comment]
Merci beaucoup!

Check it out, your translations are live in staging :)

https://deploy-preview-26--learn-redwood.netlify.app/fr/

(There may be a couple tiny bugs here and there from Crowdin)

**Comment by clairefro** [comment]
Resolved by Crowdin uploads
