### ISSUE TITLE
Could we please update reference to "Flash/useFlash" on "Saving Data" section of tutorial?

### ISSUE THREAD

**Issue by eiffel205566** [redwoodjs/learn.redwoodjs.com#81]
Hello Awesome redwood team,

Could you please update the reference to "Flash/useFlash" under "Saving Data" section of redwood tutorial as it will be replaced by Toaster and toast? Hope this will help newbies like me to avoid using the old hook.

Thank you,
Sean

**Comment by cannikin** [comment]
This issue just blew my mind—I didn't remember showing the Flash in the tutorial at all! I'll update it on Monday, thanks for noticing!

**Comment by eiffel205566** [comment]
Thanks for the quick response! Happy that I was able to contribute!

**Comment by cannikin** [comment]
Unclose! Gonna use this to track when it gets fixed. :)
