### ISSUE TITLE
New Spanish Translator

### ISSUE THREAD

**Issue by pdjota** [redwoodjs/learn.redwoodjs.com#97]
Hello @clairefro I would like to help with the translation. I did use Crowdin back 5 years ago with the OWASP when we were doing the translation of OWASP ASVS. I also did some translations of learnyounode workshops.
I'm a native Spanish speaker, currently working in London, used to co-organise JSConf.uy in Uruguay.
Regards

**Comment by clairefro** [comment]
Hi @pdjota ! Apologies for my delay in replying 

Feel free to dive in be asking for approval in Crowdin to join the project - I will approve you ASAP
https://crowdin.com/project/learn-redwoodjs/es-ES#

Here is a translation guide to help you get started
https://github.com/redwoodjs/learn.redwoodjs.com/blob/main/README_TRANSLATION_GUIDE.md

If you have any wuestions feel free to reach out in Discord translation channels
